// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicUserDetail } from "../../components/plasmic/app_codegen_demo/PlasmicUserDetail";
import { useRouter } from "next/router";
import {useAppContext} from "@/src/AppContextProvider";
import {useRef, useState} from "react";

function UserDetail() {
  const router = useRouter();
  const { actions } = useAppContext();

  const [notes, setNotes] = useState<string>();

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicUserDetail
        overrides={{
          notesInput: {
            props: {
              onChange: (event) => setNotes(event.target.value),
            },
          },
          updateButton: {
            props: {
              onClick: () => {
                if (notes !== undefined) {
                  actions.updateUserNotes({
                    id: router.query.id as string,
                    notes,
                  })
                }
              }
            }
          }
        }}
      />
    </PageParamsProvider__>
  );
}

export default UserDetail;
