// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: buzXQZLRHRnzx37qjmm2UD
// Component: SFRojVZndsn7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Module from "../../Module"; // plasmic-import: oevT7TIldYMC/component
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: buzXQZLRHRnzx37qjmm2UD/projectcss
import sty from "./PlasmicGraphModule.module.css"; // plasmic-import: SFRojVZndsn7/css

createPlasmicElementProxy;

export type PlasmicGraphModule__VariantMembers = {};
export type PlasmicGraphModule__VariantsArgs = {};
type VariantPropType = keyof PlasmicGraphModule__VariantsArgs;
export const PlasmicGraphModule__VariantProps = new Array<VariantPropType>();

export type PlasmicGraphModule__ArgsType = {};
type ArgPropType = keyof PlasmicGraphModule__ArgsType;
export const PlasmicGraphModule__ArgProps = new Array<ArgPropType>();

export type PlasmicGraphModule__OverridesType = {
  root?: Flex__<typeof Module>;
  chart?: Flex__<typeof SimpleChart>;
};

export interface DefaultGraphModuleProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGraphModule__RenderFunc(props: {
  variants: PlasmicGraphModule__VariantsArgs;
  args: PlasmicGraphModule__ArgsType;
  overrides: PlasmicGraphModule__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Module
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
      content={
        <SimpleChart
          data-plasmic-name={"chart"}
          data-plasmic-override={overrides.chart}
          className={classNames("__wab_instance", sty.chart)}
          data={[
            { region: "APAC", revenue: 3294, spend: 2675 },
            { region: "EMEA", revenue: 3245, spend: 3895 },
            { region: "LATAM", revenue: 2165, spend: 3498 },
            { region: "AMER", revenue: 3215, spend: 1656 }
          ]}
        />
      }
      title={"Graphs"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "chart"],
  chart: ["chart"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof Module;
  chart: typeof SimpleChart;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGraphModule__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGraphModule__VariantsArgs;
    args?: PlasmicGraphModule__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGraphModule__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGraphModule__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGraphModule__ArgProps,
          internalVariantPropNames: PlasmicGraphModule__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGraphModule__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGraphModule";
  } else {
    func.displayName = `PlasmicGraphModule.${nodeName}`;
  }
  return func;
}

export const PlasmicGraphModule = Object.assign(
  // Top-level PlasmicGraphModule renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    chart: makeNodeComponent("chart"),

    // Metadata about props expected for PlasmicGraphModule
    internalVariantProps: PlasmicGraphModule__VariantProps,
    internalArgProps: PlasmicGraphModule__ArgProps
  }
);

export default PlasmicGraphModule;
/* prettier-ignore-end */
